version: "3.8"

services:
  postgres-standalone:
    image: postgres:15.1
    container_name: postgres-standalone
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devsudb
    volumes:
      - ./src/main/resources/db/BaseDatos.sql:/docker-entrypoint-initdb.d/init-script.sql
#  springboot-docker-container:
#    image: springboot-docker-container
#    container_name: springboot-docker-container
#    ports:
#      - 9091:9091
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres-standalone
